name: Build Pipeline

on:
  push:
    paths-ignore:
      - '**.md'
  pull_request:
    paths-ignore:
      - '**.md'
  workflow_dispatch:
  

jobs:
  Build-Bench:
      uses: PalladioSimulator/Palladio-Build-ActionsPipeline/.github/workflows/build.yml@v3.4
      with:
          deploy-updatesite: 'products/org.palladiosimulator.product/target/deploy'
          java-version: 17
          use-display-output: true
          no-caching: true
          runner-label: ubuntu-latest
      secrets:
          SERVER_SSH_KEY: ${{ secrets.DEPLOYMENT_SERVER_SSH_KEY }}
          REMOTE_HOST: ${{ secrets.DEPLOYMENT_REMOTE_HOST }}
          REMOTE_PORT: ${{ secrets.DEPLOYMENT_REMOTE_PORT }}
          REMOTE_USER: ${{ secrets.DEPLOYMENT_REMOTE_USER }}
          REMOTE_TARGET: ${{ secrets.DEPLOYMENT_REMOTE_TARGET }}
